# Generated by Django 5.1.4 on 2024-12-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_rename_user_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
